app.name: Default applicationYaml-githug
greetings:
          msg: Merry Christmas from githug from ${app.name}
frndslist:
          values: Ram,hari,sita,gita,rita
DBproperties: "{host:'10.10.13',username:'xyz',password:'xyzz'}"
db:
   driver: jdbc.odbc.thin.driver
   host: 10.19.12.14
   port: 2222
   connection:
              serviceid: MyDB
              username: testgithug
              password: testgithug121
   schemas[0]: schema1githug
   schemas[1]: schema2githug
