server.port: 5012
app.name: configYamlgithug
greetings:
          msg: Merry Christmas from githug from ${app.name}
frndslist:
          values: Ram,hari,sita
DBproperties: "{host:'10.10.13',username:'xyz',password:'xyzz'}"
db:
   driver: jdbc.odbc.thin.driver
   host: 10.19.10.13
   port: 2222
   connection:
              serviceid: MyDB
              username: testgithug
              password: testgithug123
   schemas[0]: schema1githug
   schemas[1]: schema2githug
