server.port: 5011
app.name: configYaml
greetings:
          msg: Marry Christmas configclient git from ${app.name}
frndslist:
          values: Ram,hari,sita
DBproperties: "{host:'10.10.10',username:'xyz',password:'xyzz'}"
db:
   driver: jdbc.odbc.thin.driver
   host: 10.19.10.11
   port: 1111
   connection:
              serviceid: MyDB
              username: test
              password: test123
   schemas[0]: schema1
   schemas[1]: schema2
management.endpoints.web.exposure.include: "*"
